# Generated by Django 5.2.15 on 2026-06-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, default='default', max_length=64)),
                ('complex_id', models.CharField(max_length=200)),
                ('apt_name', models.CharField(max_length=200)),
                ('region_code', models.CharField(max_length=10)),
                ('legal_dong', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'complex_id'), name='uq_watch_owner_complex')],
            },
        ),
    ]
