# Generated by Django 5.2.15 on 2026-06-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionJobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=40)),
                ('target_date', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('fetched_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_type', 'target_date'), name='uq_job')],
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_id', models.CharField(max_length=200)),
                ('apt_name', models.CharField(max_length=200)),
                ('region_code', models.CharField(db_index=True, max_length=10)),
                ('legal_dong', models.CharField(db_index=True, max_length=100)),
                ('area_m2', models.FloatField()),
                ('price', models.BigIntegerField()),
                ('floor', models.IntegerField()),
                ('contract_date', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('complex_id', 'contract_date', 'area_m2', 'floor'), name='uq_trade_natural')],
            },
        ),
    ]
