# Generated by Django 5.2.15 on 2026-06-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='build_year',
            field=models.IntegerField(default=0),
        ),
    ]
