# Generated by Django 5.2.15 on 2026-06-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data_db', '0002_traderecord_build_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_id', models.CharField(db_index=True, max_length=200)),
                ('apt_name', models.CharField(max_length=200)),
                ('region_code', models.CharField(db_index=True, max_length=10)),
                ('legal_dong', models.CharField(db_index=True, max_length=100)),
                ('area_m2', models.FloatField()),
                ('deposit', models.BigIntegerField()),
                ('floor', models.IntegerField()),
                ('contract_date', models.DateField()),
                ('build_year', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('complex_id', 'contract_date', 'area_m2', 'floor'), name='uq_rent_natural')],
            },
        ),
    ]
