# Generated by Django 5.2.15 on 2026-06-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data_db', '0003_rentrecord'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rentrecord',
            index=models.Index(fields=['contract_date'], name='ix_rent_cd'),
        ),
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['contract_date'], name='ix_trade_cd'),
        ),
    ]
