# Generated by Django 5.2.15 on 2026-06-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data_db', '0004_rentrecord_ix_rent_cd_traderecord_ix_trade_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
