# Generated by Django 5.2.15 on 2026-06-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data_db', '0005_tickersnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=120, unique=True)),
                ('data_version', models.CharField(max_length=40)),
                ('logic_version', models.IntegerField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TickerSnapshot',
        ),
    ]
